export const mockData = {
    "album": {
        "album_type": "album",
        "artists": [
            {
                "external_urls": {
                    "spotify": "https://open.spotify.com/artist/0LyfQWJT6nXafLPZqxe9Of"
                },
                "href": "https://api.spotify.com/v1/artists/0LyfQWJT6nXafLPZqxe9Of",
                "id": "0LyfQWJT6nXafLPZqxe9Of",
                "name": "Various Artists",
                "type": "artist",
                "uri": "spotify:artist:0LyfQWJT6nXafLPZqxe9Of"
            }
        ],
        "available_markets": [
            "AE",
            "AL",
            "AR",
            "AT",
            "AU",
            "BA",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CI",
            "CL",
            "CM",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GH",
            "GR",
            "GT",
            "HK",
            "HN",
            "HR",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JP",
            "KE",
            "KH",
            "KR",
            "KW",
            "LB",
            "LK",
            "LT",
            "LU",
            "LV",
            "MA",
            "ME",
            "MK",
            "MT",
            "MX",
            "MY",
            "NG",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PT",
            "PY",
            "QA",
            "RO",
            "RS",
            "SA",
            "SE",
            "SG",
            "SI",
            "SK",
            "SN",
            "SV",
            "TH",
            "TN",
            "TR",
            "TT",
            "TW",
            "UA",
            "US",
            "UY",
            "VE",
            "VN",
            "XK",
            "ZA"
        ],
        "external_urls": {
            "spotify": "https://open.spotify.com/album/22odR710hkpaGwUFD1kqYz"
        },
        "href": "https://api.spotify.com/v1/albums/22odR710hkpaGwUFD1kqYz",
        "id": "22odR710hkpaGwUFD1kqYz",
        "images": [
            {
                "height": 640,
                "url": "https://i.scdn.co/image/ab67616d0000b2733b6886b035fe78e20fcbc8b7",
                "width": 640
            },
            {
                "height": 300,
                "url": "https://i.scdn.co/image/ab67616d00001e023b6886b035fe78e20fcbc8b7",
                "width": 300
            },
            {
                "height": 64,
                "url": "https://i.scdn.co/image/ab67616d000048513b6886b035fe78e20fcbc8b7",
                "width": 64
            }
        ],
        "name": "Finde de Hacer Oficio",
        "release_date": "2022-04-06",
        "release_date_precision": "day",
        "total_tracks": 35,
        "type": "album",
        "uri": "spotify:album:22odR710hkpaGwUFD1kqYz"
    },
    "artists": [
        {
            "external_urls": {
                "spotify": "https://open.spotify.com/artist/790FomKkXshlbRYZFtlgla"
            },
            "href": "https://api.spotify.com/v1/artists/790FomKkXshlbRYZFtlgla",
            "id": "790FomKkXshlbRYZFtlgla",
            "name": "KAROL G",
            "type": "artist",
            "uri": "spotify:artist:790FomKkXshlbRYZFtlgla"
        },
        {
            "external_urls": {
                "spotify": "https://open.spotify.com/artist/1i8SpTcr7yvPOmcqrbnVXY"
            },
            "href": "https://api.spotify.com/v1/artists/1i8SpTcr7yvPOmcqrbnVXY",
            "id": "1i8SpTcr7yvPOmcqrbnVXY",
            "name": "Ozuna",
            "type": "artist",
            "uri": "spotify:artist:1i8SpTcr7yvPOmcqrbnVXY"
        }
    ],
    "available_markets": [
        "AE",
        "AL",
        "AR",
        "AT",
        "AU",
        "BA",
        "BE",
        "BG",
        "BH",
        "BO",
        "BR",
        "CA",
        "CH",
        "CI",
        "CL",
        "CM",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FR",
        "GB",
        "GH",
        "GR",
        "GT",
        "HK",
        "HN",
        "HR",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JP",
        "KE",
        "KH",
        "KR",
        "KW",
        "LB",
        "LK",
        "LT",
        "LU",
        "LV",
        "MA",
        "ME",
        "MK",
        "MT",
        "MX",
        "MY",
        "NG",
        "NI",
        "NL",
        "NO",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PH",
        "PL",
        "PT",
        "PY",
        "QA",
        "RO",
        "RS",
        "SA",
        "SE",
        "SG",
        "SI",
        "SK",
        "SN",
        "SV",
        "TH",
        "TN",
        "TR",
        "TT",
        "TW",
        "UA",
        "US",
        "UY",
        "VE",
        "VN",
        "XK",
        "ZA"
    ],
    "disc_number": 1,
    "duration_ms": 194933,
    "explicit": false,
    "external_ids": {
        "isrc": "USUM71610032"
    },
    "external_urls": {
        "spotify": "https://open.spotify.com/track/5e1YHddQYuaVaqz5dpqKXB"
    },
    "href": "https://api.spotify.com/v1/tracks/5e1YHddQYuaVaqz5dpqKXB",
    "id": "5e1YHddQYuaVaqz5dpqKXB",
    "is_local": false,
    "name": "Hello",
    "popularity": 3,
    "preview_url": null,
    "track_number": 11,
    "type": "track",
    "uri": "spotify:track:5e1YHddQYuaVaqz5dpqKXB"
}

export let selectedData = [
  {
    album: {
      album_type: 'album',
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/1gBUSTR3TyDdTVFIaQnc02',
          },
          href: 'https://api.spotify.com/v1/artists/1gBUSTR3TyDdTVFIaQnc02',
          id: '1gBUSTR3TyDdTVFIaQnc02',
          name: 'NCT DREAM',
          type: 'artist',
          uri: 'spotify:artist:1gBUSTR3TyDdTVFIaQnc02',
        },
      ],
      available_markets: [
        'AD',
        'AE',
        'AG',
        'AL',
        'AM',
        'AO',
        'AR',
        'AT',
        'AU',
        'AZ',
        'BA',
        'BB',
        'BD',
        'BE',
        'BF',
        'BG',
        'BH',
        'BI',
        'BJ',
        'BN',
        'BO',
        'BR',
        'BS',
        'BT',
        'BW',
        'BY',
        'BZ',
        'CA',
        'CD',
        'CG',
        'CH',
        'CI',
        'CL',
        'CM',
        'CO',
        'CR',
        'CV',
        'CW',
        'CY',
        'CZ',
        'DE',
        'DJ',
        'DK',
        'DM',
        'DO',
        'DZ',
        'EC',
        'EE',
        'EG',
        'ES',
        'FI',
        'FJ',
        'FM',
        'FR',
        'GA',
        'GB',
        'GD',
        'GE',
        'GH',
        'GM',
        'GN',
        'GQ',
        'GR',
        'GT',
        'GW',
        'GY',
        'HK',
        'HN',
        'HR',
        'HT',
        'HU',
        'ID',
        'IE',
        'IL',
        'IN',
        'IQ',
        'IS',
        'IT',
        'JM',
        'JO',
        'JP',
        'KE',
        'KG',
        'KH',
        'KI',
        'KM',
        'KN',
        'KR',
        'KW',
        'KZ',
        'LA',
        'LB',
        'LC',
        'LI',
        'LK',
        'LR',
        'LS',
        'LT',
        'LU',
        'LV',
        'LY',
        'MA',
        'MC',
        'MD',
        'ME',
        'MG',
        'MH',
        'MK',
        'ML',
        'MN',
        'MO',
        'MR',
        'MT',
        'MU',
        'MV',
        'MW',
        'MX',
        'MY',
        'MZ',
        'NA',
        'NE',
        'NG',
        'NI',
        'NL',
        'NO',
        'NP',
        'NR',
        'NZ',
        'OM',
        'PA',
        'PE',
        'PG',
        'PH',
        'PK',
        'PL',
        'PS',
        'PT',
        'PW',
        'PY',
        'QA',
        'RO',
        'RS',
        'RW',
        'SA',
        'SB',
        'SC',
        'SE',
        'SG',
        'SI',
        'SK',
        'SL',
        'SM',
        'SN',
        'SR',
        'ST',
        'SV',
        'SZ',
        'TD',
        'TG',
        'TH',
        'TJ',
        'TL',
        'TN',
        'TO',
        'TR',
        'TT',
        'TV',
        'TW',
        'TZ',
        'UA',
        'UG',
        'US',
        'UY',
        'UZ',
        'VC',
        'VE',
        'VN',
        'VU',
        'WS',
        'XK',
        'ZA',
        'ZM',
        'ZW',
      ],
      external_urls: {
        spotify: 'https://open.spotify.com/album/1fRqXYwoLDxG3EwP70qnjM',
      },
      href: 'https://api.spotify.com/v1/albums/1fRqXYwoLDxG3EwP70qnjM',
      id: '1fRqXYwoLDxG3EwP70qnjM',
      images: [
        {
          height: 640,
          url: 'https://i.scdn.co/image/ab67616d0000b273e6d118f2ad157bf0bbfb83cf',
          width: 640,
        },
        {
          height: 300,
          url: 'https://i.scdn.co/image/ab67616d00001e02e6d118f2ad157bf0bbfb83cf',
          width: 300,
        },
        {
          height: 64,
          url: 'https://i.scdn.co/image/ab67616d00004851e6d118f2ad157bf0bbfb83cf',
          width: 64,
        },
      ],
      name: 'Hello Future - The 1st Album Repackage',
      release_date: '2021-06-28',
      release_date_precision: 'day',
      total_tracks: 13,
      type: 'album',
      uri: 'spotify:album:1fRqXYwoLDxG3EwP70qnjM',
    },
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/1gBUSTR3TyDdTVFIaQnc02',
        },
        href: 'https://api.spotify.com/v1/artists/1gBUSTR3TyDdTVFIaQnc02',
        id: '1gBUSTR3TyDdTVFIaQnc02',
        name: 'NCT DREAM',
        type: 'artist',
        uri: 'spotify:artist:1gBUSTR3TyDdTVFIaQnc02',
      },
    ],
    available_markets: [
      'AD',
      'AE',
      'AG',
      'AL',
      'AM',
      'AO',
      'AR',
      'AT',
      'AU',
      'AZ',
      'BA',
      'BB',
      'BD',
      'BE',
      'BF',
      'BG',
      'BH',
      'BI',
      'BJ',
      'BN',
      'BO',
      'BR',
      'BS',
      'BT',
      'BW',
      'BY',
      'BZ',
      'CA',
      'CD',
      'CG',
      'CH',
      'CI',
      'CL',
      'CM',
      'CO',
      'CR',
      'CV',
      'CW',
      'CY',
      'CZ',
      'DE',
      'DJ',
      'DK',
      'DM',
      'DO',
      'DZ',
      'EC',
      'EE',
      'EG',
      'ES',
      'FI',
      'FJ',
      'FM',
      'FR',
      'GA',
      'GB',
      'GD',
      'GE',
      'GH',
      'GM',
      'GN',
      'GQ',
      'GR',
      'GT',
      'GW',
      'GY',
      'HK',
      'HN',
      'HR',
      'HT',
      'HU',
      'ID',
      'IE',
      'IL',
      'IN',
      'IQ',
      'IS',
      'IT',
      'JM',
      'JO',
      'JP',
      'KE',
      'KG',
      'KH',
      'KI',
      'KM',
      'KN',
      'KR',
      'KW',
      'KZ',
      'LA',
      'LB',
      'LC',
      'LI',
      'LK',
      'LR',
      'LS',
      'LT',
      'LU',
      'LV',
      'LY',
      'MA',
      'MC',
      'MD',
      'ME',
      'MG',
      'MH',
      'MK',
      'ML',
      'MN',
      'MO',
      'MR',
      'MT',
      'MU',
      'MV',
      'MW',
      'MX',
      'MY',
      'MZ',
      'NA',
      'NE',
      'NG',
      'NI',
      'NL',
      'NO',
      'NP',
      'NR',
      'NZ',
      'OM',
      'PA',
      'PE',
      'PG',
      'PH',
      'PK',
      'PL',
      'PS',
      'PT',
      'PW',
      'PY',
      'QA',
      'RO',
      'RS',
      'RW',
      'SA',
      'SB',
      'SC',
      'SE',
      'SG',
      'SI',
      'SK',
      'SL',
      'SM',
      'SN',
      'SR',
      'ST',
      'SV',
      'SZ',
      'TD',
      'TG',
      'TH',
      'TJ',
      'TL',
      'TN',
      'TO',
      'TR',
      'TT',
      'TV',
      'TW',
      'TZ',
      'UA',
      'UG',
      'US',
      'UY',
      'UZ',
      'VC',
      'VE',
      'VN',
      'VU',
      'WS',
      'XK',
      'ZA',
      'ZM',
      'ZW',
    ],
    disc_number: 1,
    duration_ms: 220920,
    explicit: false,
    external_ids: {
      isrc: 'KRA302100215',
    },
    external_urls: {
      spotify: 'https://open.spotify.com/track/332GJ8ykVuEt3jOT1sy7j6',
    },
    href: 'https://api.spotify.com/v1/tracks/332GJ8ykVuEt3jOT1sy7j6',
    id: '332GJ8ykVuEt3jOT1sy7j6',
    is_local: false,
    name: 'Hello Future',
    popularity: 70,
    preview_url:
      'https://p.scdn.co/mp3-preview/bff82329372de6600d2b6b404c318964216cc0e0?cid=55548742d4374324bce1397bcea3dafc',
    track_number: 1,
    type: 'track',
    uri: 'spotify:track:332GJ8ykVuEt3jOT1sy7j6',
  },
];